---
# generate the yml using 11ty, so we can configure the CMS, from the CMS! idk if it is a good idea...
permalink: admin/config.yml
---

backend:
  name: git-gateway
  branch: main

media_folder: media/uploads" # Media files will be stored in the repo under media/uploads
public_folder: /media/uploads" # The src attribute for uploaded media will begin with /media/uploads

{% if site.url %}
site_url: {{ site.url }}
{% endif %}

collections:
  - label: Notes
    name: notes
    folder: posts/notes
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, required: false }
      - { label: Tags, name: tags, widget: list, default: ["post"]}
      - { label: Content, name: body, widget: markdown }
  - label: Images
    name: images
    folder: posts/images
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, required: false }
      - { label: Tags, name: tags, widget: list, default: ["post"]}
      - { label: Content, name: body, widget: markdown }
      - { label: File, name: file, widget: file }
  - label: Settings
    name: settings
    files:
      - label: Homepage
        name: homepage
        file: _data/homepage.json
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - { label: Sub Title, name: subtitle, widget: string, required: false }
          - { label: Menu, name: menu, widget: list, fields: [
              { label: Title, name: title, widget: string },
              { label: Url, name: url, widget: string, required: false },
              { label: Post list, name: post_list, widget: string, required: false },
              { label: Entries, name: entries, widget: list, fields: [
                { label: Title, name: title, widget: string },
                { label: Url, name: url, widget: string, required: false },
                { label: Post list, name: post_list, widget: string, required: false },
            ]}
          ]}
      - label: Site
        name: site
        file: _data/site.json
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string, required: false }
          - { label: Language, name: language, widget: string }
          - { label: Post back home text, name: back_home_text, widget: string }
          - { label: URL, name: url, widget: string, required: false }